Make regex stricter and ES2015ify
sindresorhus/mapcode-regex pull request #4
Opened 2016-09-05 23:28 UTC by kevva

Also adds `xo`, updates `ava` and `download`. I just used the regex that was posted in https://github.com/sindresorhus/mapcode-regex/issues/3#issuecomment-217388948. Might be able to optimize it a little if we need to.

2016-09-05 23:29 UTC, kevva commented on generate.js
> +	const out = `'use strict';\nmodule.exports = () => {\n\treturn /(?:(${arrayUniq(ret).sort().join('|')}) )?[ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjklmnpqrstuvwxyz0-9]{2,}[.][ABCDEFGHJKLMNPQRSTUVWXYZabcdefg
Does `[.]` and `[-]` need to be inside those square brackets? Probably not.

2016-09-05 23:29 UTC, kevva commented on generate.js
> +		if (x.Territory !== '') {
Any reason you check for `!== ''`? Noticed it was there since the first commit.

2016-09-17 14:13 UTC, sindresorhus commented on package.json
>      "prepublish": "node generate.js"
Can you rename `generate` to `make`?

2016-09-17 14:14 UTC, sindresorhus commented on generate.js
> -		var out = '\'use strict\';\nmodule.exports = function () {\n\treturn /(?:(' + arrayUniq(ret).sort().join('|') + ') )?[A-Z0-9]{2,5}\.[A-Z0-9]{2,4}/g;\n};';
You can use an inline arrow function here.

2016-09-17 14:17 UTC, sindresorhus commented on generate.js
> +	const items = new CSV(data, {header: true}).parse();
They now seem to ship a JS file too, with the data. We should rather use that.

2016-09-17 14:18 UTC, sindresorhus commented on generate.js
> +		if (x.Territory !== '') {
Non-existent data are empty strings.

2016-09-17 14:22 UTC, sindresorhus commented on generate.js
> +	const out = `'use strict';\nmodule.exports = () => {\n\treturn /(?:(${arrayUniq(ret).sort().join('|')}) )?[ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjklmnpqrstuvwxyz0-9]{2,}[.][ABCDEFGHJKLMNPQRSTUVWXYZabcdefg
No, but `.` needs to be escaped.

2016-09-17 14:23 UTC, sindresorhus commented on test.js
>  	'BR-AM 4J.Q2'
Can you add a test for:

> high precision mapcodes are specified as XX.XX-123 (with 1-8 digits).

2016-09-17 14:24 UTC, sindresorhus commented on readme.md
>  //=> true
Also update `http` to `https` in sindresorhus.com.

2016-09-17 14:24 UTC, sindresorhus requested changes

2016-09-17 17:51 UTC, kevva commented on generate.js
> -		var out = '\'use strict\';\nmodule.exports = function () {\n\treturn /(?:(' + arrayUniq(ret).sort().join('|') + ') )?[A-Z0-9]{2,5}\.[A-Z0-9]{2,4}/g;\n};';
I tried doing that at first but it broke the module.

2016-09-17 18:05 UTC, kevva commented on generate.js
> +	const items = new CSV(data, {header: true}).parse();
None of the data is exported from the file though.

2016-09-17 18:14 UTC, sindresorhus commented on generate.js
> +	const items = new CSV(data, {header: true}).parse();
I just saw that. Yeah, that's dumb. I guess it's easier to just stick with the CSV then.

Could you switch to use https://github.com/sindresorhus/neat-csv ?

2016-09-17 18:19 UTC, sindresorhus commented on generate.js
> -		var out = '\'use strict\';\nmodule.exports = function () {\n\treturn /(?:(' + arrayUniq(ret).sort().join('|') + ') )?[A-Z0-9]{2,5}\.[A-Z0-9]{2,4}/g;\n};';
Yeah, that's a V8 bug in Node.js 4. Just wrap it in parens.

2016-09-17 18:21 UTC, kevva commented on generate.js
> +	const items = new CSV(data, {header: true}).parse();
Yup, done.

2016-09-17 20:41 UTC, sindresorhus approved these changes

2016-09-17 20:41 UTC, merged

2016-09-17 20:42 UTC, sindresorhus commented
Wee. Happy to finally being able to close #3 \o/ Thank you.